### ISSUE TITLE
Home page dot animation not working

### ISSUE THREAD

**Issue by alexrandaccio** [alexrandaccio/plurality.net#1]
**Expected behavior**
The dots are supposed to arrange into characters.

![plurality-landing](https://user-images.githubusercontent.com/48193894/224111326-1b6aa8fa-10d5-4c6b-ad94-00e3b06d6367.gif)

If you want to work on this, leave a comment below and I will assign it to you!

**Comment by akinorioyama** [comment]
Dot animation sensitivity must be made more sensitive to mouse scroll and the repo may want to address non mouse user actions such as swiping.

In code **interactive-characters.js**, how about
1) setting **mutationRange** change to 10, or responsive to event.delta. The change is currently set to 1
2) adding **touchStarted** event or any equivalent that will capture swipe on device screens.
(**See** the movie below that illustrates behavior with ten full mouse rolls)

https://user-images.githubusercontent.com/12178305/224239860-d1a1f6ba-7eef-403e-89b5-f2904095340d.mp4

**Comment by akinorioyama** [comment]
I misunderstood the message because I was taking a look at the code.

There could be two types of interactions if, as the **first type**, the site retains the original intention of how digital (數位) is shown as in attached movie in my comment because those may not conflict each other. In **another interaction type**, as reported in the issue, moving over the listed language, the name of language in the chosen language could be shown in a smaller mutationRange as user's mouse goes near the center of the language text.

**Comment by alexrandaccio** [comment]
Thanks Akinori, it looks like I may have misunderstood the intended behavior. I updated the issue in light of this. I haven't had a chance to look at the code yet but will check later.

**Comment by exstalis** [comment]
Greetings, Aki, Alex

I'm also curious about your thoughts on the dotSpeed. Could it be a little slower? Also, any updates on the dots being arranged as characters and  interactive-characters.js folder changes?

**Comment by alexrandaccio** [comment]
Closed by #5
